muksapp/urls.py
from django.urls import path,include
from .views import *

app_name = 'muksapp'

urlpatterns = [
    
    path('', index, name='index'),
    path('register/', Register.as_view(), name='register'),
    path('cart/', CartView.as_view(), name='cart'),
    path('product_detail/<str:product_slug>/', product_details, name='product_detail'),
    path('category/<str:category_slug>/', category_wise, name='category'),
    path('contactus/', ContactUs.as_view(), name='contactus'),
    path('remove_item/<int:product_id>/', remove, name='remove_item'),
    path('checkout/', Checkout.as_view(), name='checkout')
]

muksgraphy/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('muksapp.urls')),
                  path('accounts/', include('django.contrib.auth.urls')),
                  path('api/', include('muksapp.api_urls')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

muksapp/models.py
from datetime import datetime
from django.contrib.auth.models import User
from django.db import models
from autoslug import AutoSlugField
from ckeditor.fields import RichTextField


class Slider(models.Model):
    brand = models.CharField(max_length=20, default='Muksgraphy')
    title = models.CharField(max_length=30)
    quotes = models.CharField(max_length=50)
    image = models.ImageField(upload_to='cms')

    def __str__(self):
        return self.title


class Category(models.Model):
    title = models.CharField(max_length=100, unique=True)
    slug = AutoSlugField(populate_from='title')

    class Meta:
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.title


class ImageCollection(models.Model):
    title = models.CharField(max_length=100, unique=True)
    slug = AutoSlugField(populate_from='title')
    category = models.ForeignKey(Category, to_field='title', on_delete=models.CASCADE)
    price = models.FloatField()
    image = models.ImageField(upload_to='images')
    descriptions = RichTextField()

    def __str__(self):
        return self.title


class Feedback(models.Model):
    name = models.CharField(max_length=50)
    email = models.EmailField()
    subject = models.CharField(max_length=100)
    feedback = models.CharField(max_length=200)

    def __str__(self):
        return self.email


class Cart(models.Model):
    user = models.ForeignKey(User, to_field='username', on_delete=models.CASCADE)
    product = models.ForeignKey(ImageCollection, to_field='title', on_delete=models.CASCADE)

    def total(self):
        return self.product.price

    def __str__(self):
        return self.product.title

class Order(models.Model):
    user = models.ForeignKey(User, to_field='username', on_delete=models.CASCADE)
    product = models.ForeignKey(ImageCollection, to_field='title', on_delete=models.CASCADE)

    def total(self):
        return self.product.price

    def __str__(self):
        return self.product.title


class ConfirmedOrder(models.Model):
    user = models.ForeignKey(User, to_field='username', on_delete=models.CASCADE)
    products = models.ManyToManyField(Order, related_name='cart')
    totalprice = models.FloatField()

    def __str__(self):
        return self.user.username


class ProductReview(models.Model):
    product = models.ForeignKey(ImageCollection, to_field='title', on_delete=models.CASCADE)
    user = models.ForeignKey(User, to_field='username', on_delete=models.DO_NOTHING)
    rating = models.IntegerField()
    comment = models.TextField()
    date = models.DateField(auto_now=True)
    time = models.TimeField(auto_now=True)

    def rating_range(self):
        return range(self.rating)

    def __str__(self):
        return self.user.username

muksapp/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect
from django.views import View
from .models import *
from .form import SignUpForm, ProductReviewForm, ContactUsForm, CheckoutForm
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

# API 
from rest_framework.permissions import AllowAny
from rest_framework.views import APIView
from django.contrib.auth import authenticate
from rest_framework.response import Response
from rest_framework import generics,status
from .serializers import *
from django.contrib.auth import logout


def index(request):
    category = Category.objects.all()
    slider = Slider.objects.all()
    recommendation1 = ImageCollection.objects.order_by('-id')[:4]
    recommendation2 = ImageCollection.objects.order_by('id')[:4]
    product = ImageCollection.objects.order_by('-id').all()
    page = request.GET.get('page')
    paginator = Paginator(product, 9)
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)
    context = {
        'categories': category,
        'products': product,
        'posts': posts,
        'recommendations1': recommendation1,
        'sliders': slider,
        'recommendations2': recommendation2,
    }
    return render(request, 'index.html', context)


class BaseView(View):
    template_context = {
        'categories': Category.objects.order_by('title').all()
    }


class CartView(LoginRequiredMixin, BaseView):

    def get(self, request):
        self.template_context['cart_items'] = Cart.objects.filter(user=request.user).order_by('-id')
        total_amount = 0

        for cart_item in self.template_context['cart_items']:
            total_amount += cart_item.total()
        self.template_context['total_amount'] = total_amount
        grand_total = (total_amount + (13 / 100) * total_amount) - (0.1 * total_amount)
        self.template_context['grand_total'] = grand_total

        return render(request, 'cart.html', self.template_context)

    def post(self, request):
        item = Cart()
        order=Order()
        product = ImageCollection.objects.get(pk=request.POST.get('product_id'))
        item.product = product
        item.user = request.user
        item.save()
        order.product = product
        order.user=request.user
        order.save()
        return redirect('/cart')


class Register(View):
    def get(self, request):
        form = SignUpForm()
        return render(request, 'registration/register.html', {'form': form})

    def post(self, request):
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('registration/login')
        else:
            messages.error(request, 'Error in creating the User. Try Again... ')
        return render(request, 'registration/register.html', {'form': form})


def product_details(request, product_slug):
    product = ImageCollection.objects.get(slug=product_slug)
    similar1 = ImageCollection.objects.order_by('-id')[:4]
    similar2 = ImageCollection.objects.order_by('id')[:4]
    recommendation1 = ImageCollection.objects.order_by('-id')[:4]
    recommendation2 = ImageCollection.objects.order_by('id')[:4]

    categories = Category.objects.all()
    form = ProductReviewForm()

    if request.method == 'POST':
        form = ProductReviewForm(request.POST)

        if form.is_valid():
            review = form.save(commit=False)
            review.product = product
            review.user = request.user
            review.save()

    context = {
        'products': product,
        'categories': categories,
        'similar1': similar1,
        'similar2': similar2,
        'recommendations1': recommendation1,
        'recommendations2': recommendation2,
        'form': form,

    }

    return render(request, 'product-details.html', context)


def category_wise(request, category_slug):
    category = Category.objects.get(slug=category_slug)
    categories = Category.objects.all()
    products = category.imagecollection_set.all()
    slider = Slider.objects.all()
    recommendation1 = ImageCollection.objects.order_by('-id')[:4]
    recommendation2 = ImageCollection.objects.order_by('id')[:4]
    page = request.GET.get('page')
    paginator = Paginator(products, 6)
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)

    context = {
        'categories': categories,
        'category': category,
        'posts': posts,
        'recommendations1': recommendation1,
        'sliders': slider,
        'recommendations2': recommendation2,
    }

    return render(request, 'category_Products.html', context)


class ContactUs(View):
    def get(self, request):
        form = ContactUsForm()
        return render(request, 'contact-us.html', {'form': form})

    def post(self, request):
        form = ContactUsForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, "Successfully submited message.")
        else:
            messages.error(request, "Error in submitting the message")
        return render(request, 'contact-us.html', {'form': form})


def remove(request, product_id):
    Cart.objects.filter(id=product_id).delete()
    return redirect('/cart')


class Checkout(View):
    def post(self, request):
        form = CheckoutForm(request.POST)
        cart = Cart.objects.filter(user=request.user)
        order = Order.objects.filter(user=request.user)
        if form.is_valid():
            confirm = form.save(commit=False)
            confirm.user = request.user
            confirm.save()
            for order_item in order:
                confirm.products.add(order_item)
            cart.delete()  
            return render(request, 'index.html')



# API View

class UserRegistrationViewSet(generics.CreateAPIView):
    queryset = User.objects.all()
    serializer_class = UserRegistrationSerializers


class UserLoginViewset(APIView):
    serializer_class = UserLoginSerializers
    permission_classes = ()

    def post(self, request):
        username = request.data.get("username")
        password = request.data.get("password")
        user = authenticate(username=username, password=password)
        if user:
            return Response({"token": user.auth_token.key})
        else:
            return Response({'error': 'Wrong Credientials'}, status=status.HTTP_400_BAD_REQUEST)

class LogoutView(APIView):
    permission_classes = (AllowAny,)

    def post(self, request):
        logout(request)
        return Response(status=status.HTTP_200_OK)

class SliderApi(APIView):
    queryset=Slider.objects.all()
    serializer_class=SliderSerializers

    def get(self,request):
        slider=Slider.objects.all()
        serializer=SliderSerializers(slider,many=True)
        return Response(serializer.data)

    def post(self,request):
        serializer=SliderSerializers(data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)


class ProductView(APIView):
    queryset=ImageCollection.objects.all()
    serializer_class=ProductSerializers

    def get(self,request):
        product=ImageCollection.objects.all()
        serializer=ProductSerializers(product,many=True)
        return Response(serializer.data)
    
    def post(self,request):
        product=ProductSerializers(data=request.data)
        
        if product.is_valid():
            product.save()
            return Response(product.data, status=status.HTTP_201_CREATED)
        return Response(product.errors, status=status.HTTP_400_BAD_REQUEST)


class ProductReviewApi(APIView):
    queryset=ProductReview.objects.all()
    serializer_class=ProductReviewSerializers

    def get(self,request):
        review=ProductReview.objects.all()
        serializer=ProductReviewSerializers(review,many=True)
        return Response(serializer.data)

    def post(self,request):
        review=ProductReviewSerializers(data=request.data)
        if review.is_valid():
            review.save()
            return Response(review.data, status=status.HTTP_201_CREATED)
        return Response(review.errors, status=status.HTTP_400_BAD_REQUEST)

class CartApi(APIView):
    queryset=Cart.objects.all()
    serializer_class=CartSerializers

    def get(self,request):
        cart=Cart.objects.all()
        serializer=CartSerializers(cart,many=True)
        return Response(serializer.data)

    def post(self,request):
        cart=CartSerializers(data=request.data)
        if cart.is_valid():
            cart.save()
            return Response(cart.data, status=status.HTTP_201_CREATED)
        return Response(cart.errors, status=status.HTTP_400_BAD_REQUEST)

class OrderApi(APIView):
    queryset=Order.objects.all()
    serializer_class=OrderSerializers

    def get(self,request):
        order=Order.objects.all()
        serializer=OrderSerializers(order,many=True)
        return Response(serializer.data)

    def post(self,request):
        order=OrderSerializers(data=request.data)
        if order.is_valid():
            order.save()
            return Response(order.data, status=status.HTTP_201_CREATED)
        return Response(order.errors, status=status.HTTP_400_BAD_REQUEST)


class ConfirmedOrderApi(APIView):
    queryset=ConfirmedOrder.objects.all()
    serializer_class=ConfirmedOrderSerializers

    def get(self,request):
        confirm=ConfirmedOrder.objects.all()
        serializer=ConfirmedOrderSerializers(confirm,many=True)
        return Response(serializer.data)

    def post(self,request):

muksapp/templates/cart.html
{% extends 'base.html' %}
{% block content %}
    <section id="cart_items">
        <div class="container">
            <div class="breadcrumbs">
                <ol class="breadcrumb">
                    <li><a href="{% url 'muksapp:index' %}">Home</a></li>
                    <li class="active">Shopping Cart</li>
                </ol>
            </div>
            <div class="table-responsive cart_info">
                <table class="table table-condensed">
                    <thead>
                    <tr class="cart_menu">
                        <td class="image">Item</td>
                        <td class="title">Title</td>
                        <td class="price">Price</td>
                        <td class="total">Total</td>
                        <td></td>
                    </tr>
                    </thead>
                    <tbody>
                    {% for cart_item in cart_items %}
                        <tr>

                            <td class="cart_product">
                                <a href=""><img src="{{ cart_item.product.image.url }}"
                                                style="height: 100px; width: 100px" alt=""></a>
                            </td>
                            <td class="cart_price">
                                <h4><a href="">{{ cart_item.product.title }}</a></h4>

                            </td>
                            <td class="cart_price">
                                <p>{{ cart_item.product.price }}</p>
                            </td>
                            <td class="cart_total">
                                <p class="cart_total_price">{{ cart_item.total }}</p>
                            </td>
                            <td class="cart_delete">
                                <a class="cart_quantity_delete" href="{% url 'muksapp:remove_item' cart_item.id %}"><i
                                        class="fa fa-times"></i></a>
                            </td>

                        </tr>
                    {% endfor %}

                    </tbody>
                </table>
            </div>
        </div>
    </section> <!--/#cart_items-->

    <section id="do_action">
        <div class="container">
            <div class="heading">
                <h3>What would you like to do next?</h3>
                <p>Choose if you have a discount code or reward points you want to use or would like to estimate your
                    delivery cost.</p>
            </div>
            <div class="row">
                <div class="col-sm-6">
                    <div class="chose_area">
                        <ul class="user_option">
                            <li>
                                <input type="checkbox">
                                <label>Use Coupon Code</label>
                            </li>
                            <li>
                                <input type="checkbox">
                                <label>Use Gift Voucher</label>
                            </li>
                            <li>
                                <input type="checkbox">
                                <label>Estimate Shipping & Taxes</label>
                            </li>
                        </ul>
                        <ul class="user_info">
                            <li class="single_field">
                                <label>Country:</label>
                                <select>
                                    <option>United States</option>
                                    <option>Bangladesh</option>
                                    <option>UK</option>
                                    <option>India</option>
                                    <option>Pakistan</option>
                                    <option>Ucrane</option>
                                    <option>Canada</option>
                                    <option>Dubai</option>
                                </select>

                            </li>
                            <li class="single_field">
                                <label>Region / State:</label>
                                <select>
                                    <option>Select</option>
                                    <option>Dhaka</option>
                                    <option>London</option>
                                    <option>Dillih</option>
                                    <option>Lahore</option>
                                    <option>Alaska</option>
                                    <option>Canada</option>
                                    <option>Dubai</option>
                                </select>

                            </li>
                            <li class="single_field zip-field">
                                <label>Zip Code:</label>
                                <input type="text">
                            </li>
                        </ul>
                        <a class="btn btn-default update" href="">Get Quotes</a>
                        <a class="btn btn-default check_out" href="">Continue</a>
                    </div>
                </div>
                <div class="col-sm-6">
                    <div class="total_area">
                        <ul>
                            <li>Cart Sub Total <span>Rs. {{ total_amount }}</span></li>
                            <li>Tax <span>13%</span></li>
                            <li>Discount <span>10%</span></li>
                            <li>Total <span>Rs. {{ grand_total }}</span></li>
                        </ul>
                        <form method="post" action="{% url 'muksapp:checkout' %}">
                            {% csrf_token %}
{#                            <input type="hidden" value="{{ request.user.username }}" name="user"/>#}
                            <input type="hidden" value="{{ grand_total }}" name="totalprice"/>
                            <div class="form-group col-md-12">
                                <input type="submit" name="Checkout" class="btn btn-primary pull-right"
                                       value="Checkout">
                            </div>
                        </form>

                    </div>
                </div>
            </div>
        </div>
    </section><!--/#do_action-->
{% endblock %}

muksapp/templates/category_Products.html
{% extends 'base.html' %}
{% load thumbnail %}
{% load static %}
{% block content %}
    <section id="slider"><!--slider-->
        <div class="container">
            <div class="row">
                <div class="col-sm-12">
                    <div id="slider-carousel" class="carousel slide" data-ride="carousel">
                        <ol class="carousel-indicators">
                            {% for slider in sliders %}
                                <li data-target="#slider-carousel" data-slide-to="{{ slider.indexes }}"
                                    class="active"></li>
                            {% endfor %}
                        </ol>

                        <div class="carousel-inner">
                            <div class="item active">
                                <div class="col-sm-6">
                                    <h1>Muksgraphy</h1>
                                    <h2>Images for life</h2>
                                    <p>Get the images that makes your life beautiful. </p>
                                </div>
                                <div class="col-sm-6">

                                    <img src="{% static 'images/slide1.jpeg' %}"
                                         style="height: 600px;width: 500px;" class="girl img-responsive"
                                         alt=""/>


                                </div>
                            </div>
                            {% for slider in sliders %}
                                <div class="item">
                                    <div class="col-sm-6">
                                        <h1>{{ slider.brand }}</h1>
                                        <h2>{{ slider.title }}</h2>
                                        <p>{{ slider.quotes }} </p>
                                    </div>
                                    <div class="col-sm-6">

                                        {% thumbnail slider.image "400x600" crop="center" as im %}
                                            <img src="{{ im.url }}" alt="" class="girl img-responsive">
                                        {% endthumbnail %}

                                    </div>

                                </div>
                            {% endfor %}


                        </div>

                        <a href="#slider-carousel" class="left control-carousel hidden-xs" data-slide="prev">
                            <i class="fa fa-angle-left"></i>
                        </a>
                        <a href="#slider-carousel" class="right control-carousel hidden-xs" data-slide="next">
                            <i class="fa fa-angle-right"></i>
                        </a>
                    </div>

                </div>
            </div>
        </div>
    </section><!--/slider-->

    <section>
        <div class="container">
            <div class="row">
                <div class="col-sm-3">
                    <div class="left-sidebar">
                        <h2>Category</h2>
                        <div class="panel-group category-products" id="accordian"><!--category-productsr-->
                            <div class="panel panel-default">
                                <div class="panel-heading">
                                    <h4 class="panel-title">
                                        {% for category in categories %}
                                            <a href="{% url 'muksapp:category' category.slug %}">
                                            {{ category.title }}<br/>
                                        {% endfor %}
                                        </a></h4>

                                </div>
                            </div>
                        </div><!--/category-products-->


                        <div class="price-range"><!--price-range-->
                            <h2>Price Range</h2>
                            <div class="well text-center">
                                <input type="text" class="span2" value="" data-slider-min="0" data-slider-max="600"
                                       data-slider-step="5" data-slider-value="[250,450]" id="sl2"><br/>
                                <b class="pull-left">$ 0</b> <b class="pull-right">$ 600</b>
                            </div>
                        </div><!--/price-range-->

                    </div>
                </div>

                <div class="col-sm-9 padding-right">
                    <h2 class="title text-center">Features Items</h2>
                    <div class="features_items">
                        {% for product in posts %}<!--features_items-->
                            <div class="col-sm-4">
                                <div class="product-image-wrapper">
                                    <div class="single-products">
                                        <a class="productinfo text-center"
                                           href="{% url 'muksapp:product_detail' product.slug %}">
                                            {#                                            <img src="{{ product.image.url }}" alt=""/>#}
                                            {% thumbnail product.image "320x300" crop="center" as pro %}
                                                <img src="{{ pro.url }}" alt="">
                                            {% endthumbnail %}
                                            <h2>Rs.{{ product.price }}</h2>
                                            <p>{{ product.title }}</p>
                                        </a>
                                    </div>
                                </div>
                            </div>
                        {% endfor %}
                    </div>

                    <center>
                        <div class="pagination" style="alignment: center">
                            {% if posts.has_other_pages %}
                                <ul class="pagination">
                                    {% if posts.has_previous %}
                                        <li><a href="?page={{ posts.previous_page_number }}">Prev</a></li>
                                    {% else %}
                                        <li class="disabled"><span>Prev</span></li>
                                    {% endif %}
                                    {% for i in posts.paginator.page_range %}
                                        {% if posts.number == i %}
                                            <li class="active"><span>{{ i }} <span
                                                    class="sr-only">(current)</span></span>
                                            </li>
                                        {% else %}
                                            <li><a href="?page={{ i }}">{{ i }}</a></li>
                                        {% endif %}
                                    {% endfor %}
                                    {% if posts.has_next %}
                                        <li><a href="?page={{ posts.next_page_number }}">Next;</a></li>
                                    {% else %}
                                        <li class="disabled"><span>Next</span></li>
                                    {% endif %}
                                </ul>
                            {% endif %}
                        </div>
                    </center>

                    <div class="recommended_items"><!--recommended_items-->
                        <h2 class="title text-center">recommended items</h2>

                        <div id="recommended-item-carousel" class="carousel slide" data-ride="carousel">
                            <div class="carousel-inner">
                                <div class="item active">
                                    {% for recommendation1 in recommendations1 %}
                                        <div class="col-sm-3">
                                            <div class="product-image-wrapper">
                                                <div class="single-products">
                                                    <div class="productinfo text-center">
                                                        {% thumbnail recommendation1.image "100x100" crop="center" as im %}
                                                            <a href="{% url 'muksapp:product_detail' recommendation1.slug %}">
                                                                <img src="{{ im.url }}" alt="">
                                                            </a>
                                                        {% endthumbnail %}
                                                        <h2>{{ recommendation1.price }}</h2>
                                                        <p>{{ recommendation1.title }}</p>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    {% endfor %}
                                </div>
                                <div class="item">
                                    {% for recommendation in recommendations2 %}
                                        <div class="col-sm-3">
                                            <div class="product-image-wrapper">
                                                <div class="single-products">
                                                    <div class="productinfo text-center">
                                                        {% thumbnail recommendation.image "100x100" crop="center" as im %}
                                                            <a href="{% url 'muksapp:product_detail' recommendation.slug %}">
                                                                <img src="{{ im.url }}" alt="">
                                                            </a>
                                                        {% endthumbnail %}
                                                        <h2>{{ recommendation.price }}</h2>
                                                        <p>{{ recommendation.title }}</p>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    {% endfor %}
                                </div>
                            </div>
                            <a class="left recommended-item-control" href="#recommended-item-carousel"
                               data-slide="prev">
                                <i class="fa fa-angle-left"></i>
                            </a>
                            <a class="right recommended-item-control" href="#recommended-item-carousel"
                               data-slide="next">
                                <i class="fa fa-angle-right"></i>
                            </a>
                        </div>
                    </div><!--/recommended_items-->
                </div>
            </div>
        </div>
    </section>

{% endblock %}